### ISSUE TITLE
Hi Juan, can I translate your grate articles into Chinese?

### ISSUE THREAD

**Issue by CodingPapi** [juanchosaravia/KedditBySteps#1]
Sorry to open an issue here,
I cannot write a response  under your article in Medium

I really enjoy reading your articles, 
Can I translate them into Chinese?
I want publish them in my blog

Thanks for your great work.

**Comment by zazk** [comment]
Hi @CodingPapi would be great to translate the 10 parts in this repository and sent the PR.

**Comment by CodingPapi** [comment]
@zazk Thanks！

**Comment by juanchosaravia** [comment]
@CodingPapi sorry for the late response but for sure fell free to translate any article.

**Comment by CodingPapi** [comment]
@juanchosaravia Thank U!!!

**Comment by juanchosaravia** [comment]
@CodingPapi please share the link when you have it done 👍 thanks man!!

**Comment by zazk** [comment]
Great Work

**Comment by CodingPapi** [comment]
@juanchosaravia Of course I will
