### ISSUE TITLE
Missing Part 10: Adding Dagger 2

### ISSUE THREAD

**Issue by multlurk** [juanchosaravia/KedditBySteps#15]
Hello. Thank you for your work.
The page http://www.andevcon.com/news/keddit-part-10-kotlin-dagger-2-dependency-injection with your article "Part 10: Adding Dagger 2" is not available. Where can I read this?

**Comment by juanchosaravia** [comment]
Sorry about this, they just removed it without saying anything :( 

I just updated the Part 10 with the same content:
https://android.jlelse.eu/keddit-part-10-kotlin-dagger-2-dependency-injection-a620052a7384
